name: Deployment

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # validate gradle wrapper signature
      - uses: gradle/wrapper-validation-action@v1

      # capture the latest tag
      - name: Set environment variables
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      # Gradle caching and more
      - name: Publish to Repository
        uses: gradle/gradle-build-action@v2
        with:
          arguments: 'publish --stacktrace'
        env:
          CI_VERSION: ${{ steps.vars.outputs.tag }}
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}